import { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { expenseSchema, fuelSchema, tripSchema, tripStartSchema, tripEndSchema, startSessionSchema, closeSessionSchema } from '../domain/schemas.js';
import { closeSession, startSession } from '../db/session-repository.js';
import { createExpense, createFuel, createTrip, endTrip } from '../db/transaction-repository.js';
import { authErrorResponse, requireDriver } from '../auth/driver-auth.js';
const syncItemSchema=z.object({type:z.enum(['SESSION_START','TRIP_START','TRIP_END','TRIP','FUEL','EXPENSE','SESSION_CLOSE']),payload:z.record(z.string(),z.unknown())});
const syncSchema=z.object({transactions:z.array(syncItemSchema).min(1).max(100)}).superRefine((value,ctx)=>{const ids=value.transactions.map(i=>i.payload.clientTransactionId).filter((id):id is string=>typeof id==='string');const seen=new Set<string>();ids.forEach((id,index)=>{if(seen.has(id))ctx.addIssue({code:'custom',path:['transactions',index,'payload','clientTransactionId'],message:'Duplicate client transaction ID in sync batch'});seen.add(id);});});
function syncErrorCode(error:unknown):string{if(error instanceof z.ZodError)return'VALIDATION_ERROR';const message=error instanceof Error?error.message:String(error);const known=['DRIVER_VEHICLE_NOT_ASSIGNED','VEHICLE_NOT_ACTIVE','SESSION_ALREADY_OPEN','NO_OPEN_SESSION','SESSION_CLOSED','SESSION_DRIVER_MISMATCH','SESSION_VEHICLE_MISMATCH','SESSION_IDENTITY_MISMATCH','SESSION_NOT_OPEN','INVALID_CLOSE_ODOMETER','CLOSE_TIME_BEFORE_START','SESSION_ID_MISMATCH','ODOMETER_REGRESSION','FUEL_AMOUNT_MISMATCH','SESSION_NOT_FOUND','TRIP_NOT_FOUND','TRIP_IDENTITY_MISMATCH','TRIP_END_TIME_BEFORE_START','TRIP_ALREADY_IN_PROGRESS','TRIP_IN_PROGRESS','GPS_REQUIRED','GPS_INVALID_COORDINATES','GPS_ACCURACY_TOO_LOW','GPS_STALE'];return known.find(v=>message.includes(v))??'SYNC_FAILED';}
export async function registerSyncRoutes(app:FastifyInstance){app.post('/v1/sync',async(request,reply)=>{let identity;try{identity=await requireDriver(request);}catch(error){const response=authErrorResponse(error);if(response)return reply.code(response.status).send(response.body);throw error;}const parsed=syncSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',details:parsed.error.issues});const results=[];for(const item of parsed.data.transactions){const clientTransactionId=typeof item.payload.clientTransactionId==='string'?item.payload.clientTransactionId:null;try{let result:Record<string,unknown>;switch(item.type){case'SESSION_START':{const body=startSessionSchema.parse(item.payload);result=await startSession({...body,driverId:identity.driverId,vehicleId:identity.vehicleId});break;}case'TRIP_START':{const body=tripStartSchema.parse(item.payload);result=await createTrip({...body,driverId:identity.driverId,vehicleId:identity.vehicleId,status:'IN_PROGRESS',endedAt:null});break;}case'TRIP_END':{const body=tripEndSchema.parse(item.payload);result=await endTrip({...body,driverId:identity.driverId,vehicleId:identity.vehicleId});break;}case'TRIP':{const body=tripSchema.parse(item.payload);result=await createTrip({...body,driverId:identity.driverId,vehicleId:identity.vehicleId});break;}case'FUEL':{const body=fuelSchema.parse(item.payload);result=await createFuel({...body,driverId:identity.driverId,vehicleId:identity.vehicleId});break;}case'EXPENSE':{const body=expenseSchema.parse(item.payload);result=await createExpense({...body,driverId:identity.driverId,vehicleId:identity.vehicleId});break;}case'SESSION_CLOSE':{const body=closeSessionSchema.parse(item.payload);result=await closeSession({...body,driverId:identity.driverId,vehicleId:identity.vehicleId});break;}}results.push({type:item.type,clientTransactionId,accepted:true,result});}catch(error){results.push({type:item.type,clientTransactionId,accepted:false,error:syncErrorCode(error)});}}return{accepted:results.filter(r=>r.accepted).length,rejected:results.filter(r=>!r.accepted).length,results};});}
