import React,{useCallback,useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient,Session}from'@supabase/supabase-js';
import'./style.css';

const API=import.meta.env.VITE_API_BASE_URL||'https://cab-application-z4ow.onrender.com';
const SB=createClient(import.meta.env.VITE_SUPABASE_URL||'',import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY||'');
const CTX_KEY='cab-pwa-context',SESSION_KEY='cab-session-id',QUEUE_KEY='cab-pwa-queue';
type C={userId:string;driverId:string;displayName:string;vehicleId?:string;registrationNumber?:string;currentOdometer?:number;today?:{trips?:number;distanceKm?:number;earnings?:number}};
type Q={id:string;type:string;body:any;status:'PENDING_SYNC'|'FAILED';attempts:number;lastError?:string;createdAt:string};

function lsRead<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function lsWrite(key:string,value:any){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function openQueueDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(Error('IndexedDB unavailable'));const r=indexedDB.open('cab-driver',1);r.onupgradeneeded=()=>r.result.createObjectStore('queue',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||Error('IndexedDB error'))})}
async function queueGet():Promise<Q[]>{try{const db=await openQueueDb();return await new Promise((res,rej)=>{const r=db.transaction('queue','readonly').objectStore('queue').getAll();r.onsuccess=()=>res((r.result||[])as Q[]);r.onerror=()=>rej(r.error)})}catch{return lsRead<Q[]>(QUEUE_KEY,[])}}
async function queuePut(x:Q){try{const db=await openQueueDb();await new Promise((res,rej)=>{const r=db.transaction('queue','readwrite').objectStore('queue').put(x);r.onsuccess=()=>res(null);r.onerror=()=>rej(r.error)});return}catch{}const q=lsRead<Q[]>(QUEUE_KEY,[]).filter(y=>y.id!==x.id);lsWrite(QUEUE_KEY,[...q,x])}
async function queueDelete(id:string){try{const db=await openQueueDb();await new Promise((res,rej)=>{const r=db.transaction('queue','readwrite').objectStore('queue').delete(id);r.onsuccess=()=>res(null);r.onerror=()=>rej(r.error)});return}catch{}lsWrite(QUEUE_KEY,lsRead<Q[]>(QUEUE_KEY,[]).filter(x=>x.id!==id))}
async function queueReplace(q:Q[]){for(const x of q)await queuePut(x)}
async function api(path:string,token:string,body?:any){const r=await fetch(API+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const text=await r.text();let data:any={};try{data=JSON.parse(text)}catch{}if(!r.ok){const e:any=Error(data.code||data.error||('HTTP '+r.status));e.status=r.status;e.data=data;throw e}return data}
function gps():Promise<{latitude:number;longitude:number;accuracy:number;at:string}>{return new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(p=>res({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,at:new Date().toISOString()}),rej,{enableHighAccuracy:true,timeout:10000,maximumAge:0}))}

function App(){
 const[s,setS]=useState<Session|null>(null),[ctx,setCtx]=useState<C|null>(()=>lsRead<C|null>(CTX_KEY,null)),[loading,setLoading]=useState(true),[screen,setScreen]=useState(lsRead<C|null>(CTX_KEY,null)?'home':'login'),[offline,setOffline]=useState(!navigator.onLine),[queue,setQueue]=useState<Q[]>([]),[err,setErr]=useState(''),[sessionId,setSessionId]=useState<string|null>(()=>localStorage.getItem(SESSION_KEY)),[odo,setOdo]=useState(''),[trip,setTrip]=useState({start:'',end:'',fare:'',pickup:'',dropoff:'',paymentMethod:'CASH' as const,toll:'0',parking:'0'}),[fuel,setFuel]=useState({odometer:'',quantity:'',rate:'',paymentMethod:'CASH' as const}),[expense,setExpense]=useState({amount:'',categoryId:'',odometer:'',paymentMethod:'CASH' as const,notes:''});
 const syncing=useRef(false);
 const refreshQueue=useCallback(async()=>setQueue(await queueGet()),[]);
 const refresh=useCallback(async(sess:Session|null,initial=false)=>{if(!sess)return;try{const d=await api('/v1/me/driver-context',sess.access_token);const c=d.context||d;lsWrite(CTX_KEY,c);setCtx(c);setScreen('home');setErr('')}catch(e){if(ctx||lsRead<C|null>(CTX_KEY,null)){setScreen('home');setErr('Offline mode: using cached driver profile')}else if(initial)setScreen('login')}},[ctx]);
 useEffect(()=>{const on=()=>setOffline(!navigator.onLine);addEventListener('online',on);addEventListener('offline',on);navigator.serviceWorker?.register('/sw.js').catch(()=>{});(async()=>{await refreshQueue();const {data}=await SB.auth.getSession();setS(data.session);if(data.session)await refresh(data.session,true);setLoading(false)})();return()=>{removeEventListener('online',on);removeEventListener('offline',on)}},[refreshQueue,refresh]);
 const enqueue=useCallback(async(type:string,body:any)=>{const x:Q={id:crypto.randomUUID(),type,body,status:'PENDING_SYNC',attempts:0,createdAt:new Date().toISOString()};await queuePut(x);await refreshQueue();return x.id},[refreshQueue]);
 const sync=useCallback(async()=>{if(syncing.current||!navigator.onLine)return;syncing.current=true;try{const {data}=await SB.auth.getSession();if(!data.session){setS(null);return}setS(data.session);let q=(await queueGet()).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));for(const x of q){if(x.status==='FAILED'&&x.attempts>=5)continue;try{let token=data.session.access_token;let path='';if(x.type==='SESSION_START')path='/v1/sessions';else if(x.type==='SESSION_CLOSE')path='/v1/sessions/'+x.body.sessionId+'/close';else if(x.type==='TRIP')path='/v1/trips';else if(x.type==='FUEL')path='/v1/fuel';else if(x.type==='EXPENSE')path='/v1/expenses';else continue;try{await api(path,token,x.body)}catch(e:any){if(e?.status===401){const rr=await SB.auth.refreshSession();if(rr.data.session){setS(rr.data.session);await api(path,rr.data.session.access_token,x.body)}else throw e}else throw e}await queueDelete(x.id);if(x.type==='SESSION_CLOSE'){localStorage.removeItem(SESSION_KEY);setSessionId(null)}await refreshQueue()}catch(e:any){const y={...x,status:'FAILED' as const,attempts:x.attempts+1,lastError:String(e?.data?.error||e?.message||e)};await queuePut(y);await refreshQueue();if(y.attempts>=5)continue;break}}}finally{syncing.current=false}},[refreshQueue]);
 useEffect(()=>{if(!loading){sync();const t=setInterval(sync,30000);return()=>clearInterval(t)}},[loading,s,sync]);
 useEffect(()=>{const h=()=>sync();addEventListener('online',h);return()=>removeEventListener('online',h)},[sync]);

 async function login(email:string,password:string){setErr('');const{data,error}=await SB.auth.signInWithPassword({email,password});if(error){setErr(error.message);return}setS(data.session);await refresh(data.session)}
 async function logout(){if(queue.some(x=>x.status==='PENDING_SYNC')){setErr('Sync pending data before logout');return}await SB.auth.signOut();localStorage.removeItem(CTX_KEY);localStorage.removeItem(SESSION_KEY);setCtx(null);setSessionId(null);setS(null);setScreen('login')}
 async function start(){if(!ctx?.vehicleId||!s){setErr('Driver/vehicle is not ready');return}const n=Number(odo);if(!Number.isFinite(n)||n<0){setErr('Enter a valid odometer');return}let g;try{g=await gps()}catch{setErr('GPS is required to start a session');return}if(g.accuracy>50){setErr('GPS accuracy must be 50m or better');return}const id=crypto.randomUUID();const now=new Date().toISOString();const body={clientTransactionId:id,sessionId:id,startedAt:now,startOdometer:n,startLat:g.latitude,startLng:g.longitude,startAccuracyM:g.accuracy,startGpsAt:g.at};await enqueue('SESSION_START',body);localStorage.setItem(SESSION_KEY,id);setSessionId(id);setOdo('');setScreen('home');await sync()}
 async function addTrip(){if(!sessionId){setErr('Start a session first');return}const st=Number(trip.start),en=Number(trip.end),fare=Number(trip.fare),toll=Number(trip.toll)||0,parking=Number(trip.parking)||0;if(![st,en,fare].every(Number.isFinite)||en<st||fare<0){setErr('Check trip odometers and fare');return}const body={clientTransactionId:crypto.randomUUID(),sessionId,startedAt:new Date().toISOString(),endedAt:new Date().toISOString(),startOdometer:st,endOdometer:en,grossFare:fare,pickup:trip.pickup||null,dropoff:trip.dropoff||null,paymentMethod:trip.paymentMethod,additionalCharges:toll+parking,status:'COMPLETED',gpsAt:null};await enqueue('TRIP',body);setTrip({start:'',end:'',fare:'',pickup:'',dropoff:'',paymentMethod:'CASH',toll:'0',parking:'0'});setScreen('home');await sync()}
 async function addFuel(){if(!sessionId){setErr('Start a session first');return}const od=Number(fuel.odometer),qty=Number(fuel.quantity),rate=Number(fuel.rate),amount=Math.round(qty*rate*100)/100;if(![od,qty,rate].every(Number.isFinite)||qty<=0||rate<0){setErr('Enter valid fuel details');return}const body={clientTransactionId:crypto.randomUUID(),sessionId,fuelType:'CNG',odometer:od,quantity:qty,unit:'KG',rate,amount,paymentMethod:fuel.paymentMethod,recordedAt:new Date().toISOString()};await enqueue('FUEL',body);setFuel({odometer:'',quantity:'',rate:'',paymentMethod:'CASH'});setScreen('home');await sync()}
 async function addExpense(){if(!sessionId){setErr('Start a session first');return}const amount=Number(expense.amount),od=expense.odometer?Number(expense.odometer):undefined;if(!Number.isFinite(amount)||amount<=0||od!==undefined&&!Number.isFinite(od)){setErr('Enter a valid expense');return}const body={clientTransactionId:crypto.randomUUID(),sessionId,categoryId:expense.categoryId||null,amount,paymentMethod:expense.paymentMethod,odometer:od??null,recordedAt:new Date().toISOString(),notes:expense.notes||null};await enqueue('EXPENSE',body);setExpense({amount:'',categoryId:'',odometer:'',paymentMethod:'CASH',notes:''});setScreen('home');await sync()}
 async function closeSession(){if(!sessionId){setErr('No active session');return}if(queue.some(x=>x.type==='SESSION_START'&&x.body.sessionId===sessionId)){setErr('Session start is still waiting to sync');return}const n=Number(odo);if(!Number.isFinite(n)||n<0){setErr('Enter a valid closing odometer');return}let g;try{g=await gps()}catch{setErr('GPS is required to close the session');return}if(g.accuracy>50){setErr('GPS accuracy must be 50m or better');return}const today=ctx?.today||{};const body={clientTransactionId:crypto.randomUUID(),sessionId,closedAt:new Date().toISOString(),closeOdometer:n,closeLat:g.latitude,closeLng:g.longitude,closeAccuracyM:g.accuracy,closeGpsAt:g.at,reportedTripCount:Number(today.trips||0),reportedIncome:Number(today.earnings||0)};await enqueue('SESSION_CLOSE',body);setOdo('');setScreen('home');await sync()}

 if(loading)return <main><h2>Cab Ops</h2><p>Restoring driver session…</p></main>;
 if(screen==='login')return <Login onLogin={login} error={err}/>;
 if(screen==='start')return <Odo title="Start Session" value={odo} setValue={setOdo} onBack={()=>setScreen('home')} onSubmit={start} action="START SESSION"/>;
 if(screen==='close')return <Odo title="End Session" value={odo} setValue={setOdo} onBack={()=>setScreen('home')} onSubmit={closeSession} action="END SESSION"/>;
 if(screen==='trip')return <Trip t={trip} setT={setTrip} onBack={()=>setScreen('home')} onSave={addTrip}/>;
 if(screen==='fuel')return <Fuel f={fuel} setF={setFuel} onBack={()=>setScreen('home')} onSave={addFuel}/>;
 if(screen==='expense')return <Expense e={expense} setE={setExpense} onBack={()=>setScreen('home')} onSave={addExpense}/>;
 return <main><header><div><b>Cab Ops</b><div className="muted">{ctx?.displayName} • {ctx?.registrationNumber||'No vehicle'}</div></div><button onClick={logout}>Logout</button></header>{offline&&<div className="banner">OFFLINE • Saved locally • auto-sync when online</div>}{err&&<div className="error">{err}</div>}<section className="card"><small>TODAY</small><div className="stats"><b>{ctx?.today?.trips||0}<small>Trips</small></b><b>{Number(ctx?.today?.distanceKm||0).toFixed(1)}<small>KM</small></b><b>₹{Number(ctx?.today?.earnings||0).toFixed(0)}<small>Earnings</small></b></div></section>{sessionId?<section className="card"><h2>SESSION ACTIVE</h2><p>Session is safely stored on this device.</p><div className="grid"><button className="primary" onClick={()=>setScreen('trip')}>ADD TRIP</button><button onClick={()=>setScreen('fuel')}>ADD FUEL</button><button onClick={()=>setScreen('expense')}>ADD EXPENSE</button><button onClick={()=>setScreen('close')}>END SESSION</button></div></section>:<section className="card"><h2>READY TO WORK</h2><button className="primary wide" onClick={()=>{setOdo(String(ctx?.currentOdometer??''));setScreen('start')}}>START SESSION</button></section>}<section className="card"><b>SYNC STATUS</b><p>{queue.length===0?'All saved data is synced.':queue.filter(x=>x.status==='PENDING_SYNC').length+' pending • '+queue.filter(x=>x.status==='FAILED').length+' failed'}</p><button onClick={sync}>SYNC NOW</button></section></main>
}
function Login({onLogin,error}:{onLogin:(e:string,p:string)=>void;error:string}){const[e,setE]=useState(''),[p,setP]=useState('');return <main><div className="login"><h1>Cab Ops</h1><p>Driver login</p><input autoComplete="username" placeholder="Email" value={e} onChange={x=>setE(x.target.value)}/><input autoComplete="current-password" placeholder="Password" type="password" value={p} onChange={x=>setP(x.target.value)}/><button className="primary wide" onClick={()=>onLogin(e.trim(),p)}>SIGN IN</button>{error&&<div className="error">{error}</div>}</div></main>}
function Odo({title,value,setValue,onBack,onSubmit,action}:{title:string;value:string;setValue:(v:string)=>void;onBack:()=>void;onSubmit:()=>void;action:string}){return <main><h2>{title}</h2><p>Odometer (km)</p><input className="odo" inputMode="numeric" autoFocus value={value} onChange={e=>setValue(e.target.value.replace(/[^0-9.]/g,''))}/><div className="row"><button onClick={onBack}>CANCEL</button><button className="primary" onClick={onSubmit}>{action}</button></div></main>}
function Trip({t,setT,onBack,onSave}:{t:any;setT:(x:any)=>void;onBack:()=>void;onSave:()=>void}){const f=(k:string)=>(e:any)=>setT({...t,[k]:e.target.value});return <main><h2>Add Trip</h2><input inputMode="numeric" placeholder="Start odometer" value={t.start} onChange={f('start')}/><input inputMode="numeric" placeholder="End odometer" value={t.end} onChange={f('end')}/><input inputMode="decimal" placeholder="Gross fare ₹" value={t.fare} onChange={f('fare')}/><input placeholder="Pickup (optional)" value={t.pickup} onChange={f('pickup')}/><input placeholder="Dropoff (optional)" value={t.dropoff} onChange={f('dropoff')}/><select value={t.paymentMethod} onChange={f('paymentMethod')}><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK</option><option>OTHER</option></select><input inputMode="decimal" placeholder="Toll ₹" value={t.toll} onChange={f('toll')}/><input inputMode="decimal" placeholder="Parking ₹" value={t.parking} onChange={f('parking')}/><div className="row"><button onClick={onBack}>CANCEL</button><button className="primary" onClick={onSave}>SAVE TRIP</button></div></main>}
function Fuel({f,setF,onBack,onSave}:{f:any;setF:(x:any)=>void;onBack:()=>void;onSave:()=>void}){const g=(k:string)=>(e:any)=>setF({...f,[k]:e.target.value});return <main><h2>Add CNG</h2><input inputMode="numeric" placeholder="Odometer" value={f.odometer} onChange={g('odometer')}/><input inputMode="decimal" placeholder="Quantity (KG)" value={f.quantity} onChange={g('quantity')}/><input inputMode="decimal" placeholder="Rate ₹/KG" value={f.rate} onChange={g('rate')}/><select value={f.paymentMethod} onChange={g('paymentMethod')}><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK</option><option>OTHER</option></select><div className="row"><button onClick={onBack}>CANCEL</button><button className="primary" onClick={onSave}>SAVE FUEL</button></div></main>}
function Expense({e,setE,onBack,onSave}:{e:any;setE:(x:any)=>void;onBack:()=>void;onSave:()=>void}){const g=(k:string)=>(x:any)=>setE({...e,[k]:x.target.value});return <main><h2>Add Expense</h2><input inputMode="decimal" placeholder="Amount ₹" value={e.amount} onChange={g('amount')}/><input placeholder="Category ID (optional)" value={e.categoryId} onChange={g('categoryId')}/><input inputMode="numeric" placeholder="Odometer (optional)" value={e.odometer} onChange={g('odometer')}/><select value={e.paymentMethod} onChange={g('paymentMethod')}><option>CASH</option><option>UPI</option><option>CARD</option><option>BANK</option><option>OTHER</option></select><input placeholder="Notes (optional)" value={e.notes} onChange={g('notes')}/><div className="row"><button onClick={onBack}>CANCEL</button><button className="primary" onClick={onSave}>SAVE EXPENSE</button></div></main>}
createRoot(document.getElementById('root')!).render(<App/>);