import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./styles.css';
const API=import.meta.env.VITE_API_BASE_URL||'https://cab-application-z4ow.onrender.com';const sb=createClient(import.meta.env.VITE_SUPABASE_URL||'',import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'');const uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),n=v=>Number(v||0);
const db=()=>new Promise((res,rej)=>{const r=indexedDB.open('cab-driver',1);r.onupgradeneeded=()=>r.result.createObjectStore('queue',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
async function add(item){const d=await db();return new Promise((res,rej)=>{const t=d.transaction('queue','readwrite');t.objectStore('queue').put({id:uid(),...item});t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function all(){const d=await db();return new Promise((res,rej)=>{const r=d.transaction('queue').objectStore('queue').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function del(id){const d=await db();return new Promise((res,rej)=>{const t=d.transaction('queue','readwrite');t.objectStore('queue').delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
const gps=()=>new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(p=>res({latitude:p.coords.latitude,longitude:p.coords.longitude,gpsAccuracyM:p.coords.accuracy}),rej,{enableHighAccuracy:true,timeout:12000,maximumAge:15000}));
function App(){const[signed,setSigned]=useState(false),[email,setEmail]=useState(''),[session,setSession]=useState(null),[queue,setQueue]=useState(0),[msg,setMsg]=useState('');
useEffect(()=>{sb.auth.getSession().then(({data})=>{setSigned(!!data.session);setEmail(data.session?.user?.email||'')});navigator.serviceWorker?.register('/sw.js');sync()},[]);
async function sync(){const{data:{session}}=await sb.auth.getSession();const items=await all();setQueue(items.length);if(!session||!items.length)return;const r=await fetch(API+'/v1/sync',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({transactions:items.map(x=>({type:x.type,payload:x.payload}))})});if(!r.ok)return;const out=await r.json();for(const x of out.results||[])if(x.accepted){const i=items.find(v=>v.payload.clientTransactionId===x.clientTransactionId);if(i)await del(i.id)}setQueue((await all()).length)}
async function api(path,payload){const{data:{session}}=await sb.auth.getSession();if(!session)throw Error('LOGIN_REQUIRED');const r=await fetch(API+path,{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error((await r.json().catch(()=>({}))).error||'REQUEST_FAILED');return r.json()}
async function save(type,path,payload){try{await api(path,payload);setMsg('Saved');}catch(e){await add({type,payload});setMsg('Saved offline — will sync');}await sync()}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),{error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)return setMsg(error.message);setSigned(true);setEmail(String(f.get('email')))}
async function start(){try{const g=await gps(),od=n(prompt('Start odometer'));if(!Number.isFinite(od)||od<0)return;const p={clientTransactionId:uid(),sessionId:uid(),startedAt:now(),startOdometer:od,startLat:g.latitude,startLng:g.longitude,startAccuracyM:g.gpsAccuracyM,startGpsAt:now(),notes:null};try{await api('/v1/sessions',p)}catch(e){await add({type:'SESSION_START',payload:p});setMsg('Session saved offline')}setSession({id:p.sessionId,odometer:od,startedAt:p.startedAt});await sync()}catch(e){setMsg(e.message)}}
async function trip(){if(!session)return;try{const g=await gps(),start=n(prompt('Trip start odometer',session.odometer)),end=n(prompt('Trip end odometer',start)),fare=n(prompt('Gross fare')),pickup=prompt('Pickup')||null,drop=prompt('Drop')||null,payment=prompt('Payment: CASH / UPI / CARD / BANK / OTHER','UPI');const p={clientTransactionId:uid(),sessionId:session.id,startedAt:now(),endedAt:now(),pickup,dropoff:drop,startOdometer:start,endOdometer:end,grossFare:fare,paymentMethod:payment,additionalCharges:0,status:'COMPLETED',latitude:g.latitude,longitude:g.longitude,gpsAccuracyM:g.gpsAccuracyM,gpsAt:now(),notes:null};await save('TRIP','/v1/trips',p);setSession({...session,odometer:end})}catch(e){setMsg(e.message)}}
async function fuel(){if(!session)return;try{const g=await gps(),od=n(prompt('Odometer',session.odometer)),q=n(prompt('Quantity (kg)')),rate=n(prompt('Rate')),p={clientTransactionId:uid(),sessionId:session.id,fuelType:'CNG',odometer:od,quantity:q,unit:'kg',rate,amount:q*rate,paymentMethod:'CASH',receiptFileId:null,latitude:g.latitude,longitude:g.longitude,gpsAccuracyM:g.gpsAccuracyM,recordedAt:now(),notes:null};await save('FUEL','/v1/fuel',p)}catch(e){setMsg(e.message)}}
async function expense(){if(!session)return;try{const g=await gps(),amount=n(prompt('Expense amount')),p={clientTransactionId:uid(),sessionId:session.id,categoryId:null,amount,paymentMethod:'CASH',proofFileId:null,odometer:session.odometer,latitude:g.latitude,longitude:g.longitude,gpsAccuracyM:g.gpsAccuracyM,recordedAt:now(),notes:prompt('Note')||null};await save('EXPENSE','/v1/expenses',p)}catch(e){setMsg(e.message)}}
async function close(){if(!session)return;try{const g=await gps(),od=n(prompt('Close odometer',session.odometer)),count=n(prompt('Reported trip count')),income=n(prompt('Reported income')),p={clientTransactionId:uid(),sessionId:session.id,closedAt:now(),closeOdometer:od,closeLat:g.latitude,closeLng:g.longitude,closeAccuracyM:g.gpsAccuracyM,closeGpsAt:now(),closeOdometerFileId:null,reportedTripCount:count,reportedIncome:income,notes:null};try{await api('/v1/sessions/'+session.id+'/close',p)}catch(e){await add({type:'SESSION_CLOSE',payload:p});setMsg('Close saved offline')}setSession(null);await sync()}catch(e){setMsg(e.message)}}
if(!signed)return <main><section className="card"><h1>Cab Driver</h1><p>Operations PWA</p><form onSubmit={login}><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" required/><button>Sign in</button></form><p>{msg}</p></section></main>;
return <main><header><div><b>Cab Driver</b><small>{email}</small></div><button onClick={async()=>{await sb.auth.signOut();setSigned(false)}}>Sign out</button></header><div className="status">{navigator.onLine?'Online':'Offline'} · Pending sync: {queue}</div>{msg&&<p>{msg}</p>}{session?<><section className="hero"><small>OPEN SESSION</small><strong>{session.odometer.toFixed(1)} km</strong><span>{new Date(session.startedAt).toLocaleString()}</span></section><div className="grid"><button onClick={trip}>＋ Trip</button><button onClick={fuel}>⛽ Fuel</button><button onClick={expense}>₹ Expense</button><button className="danger" onClick={close}>Close Session</button></div></>:<button className="start" onClick={start}>🌅 Start Session</button>}<button className="secondary" onClick={sync}>Sync Now</button></main>}
createRoot(document.getElementById('root')).render(<App/>);