import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{createClient,Session}from'@supabase/supabase-js';import'./style.css';
const API=import.meta.env.VITE_API_BASE_URL||'https://cab-application-z4ow.onrender.com';const SB=createClient(import.meta.env.VITE_SUPABASE_URL||'',import.meta.env.VITE_SUPABASE_ANON_KEY||'');
type C={userId:string;driverId:string;displayName:string;vehicleId?:string;registrationNumber?:string;currentOdometer?:number;today?:any};type Q={id:string;type:string;body:any;status:string};
const key='cab-pwa-context';const qkey='cab-pwa-queue';const readQ=():Q[]=>JSON.parse(localStorage.getItem(qkey)||'[]');const saveQ=(q:Q[])=>localStorage.setItem(qkey,JSON.stringify(q));
async function api(path:string,token:string,body?:any){const r=await fetch(API+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const text=await r.text();let data:any={};try{data=JSON.parse(text)}catch{}if(!r.ok)throw Error(data.code||data.error||('HTTP '+r.status));return data}
function App(){const[s,setS]=useState<Session|null>(null),[ctx,setCtx]=useState<C|null>(()=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}),[loading,setLoading]=useState(true),[screen,setScreen]=useState(ctx?'home':'login'),[offline,setOffline]=useState(!navigator.onLine),[queue,setQueue]=useState(readQ()),[err,setErr]=useState('');const[sessionId,setSessionId]=useState<string|null>(()=>localStorage.getItem('cab-session-id'));const[odo,setOdo]=useState(''),[photo,setPhoto]=useState(''),[trip,setTrip]=useState({start:'',end:'',fare:'',pickup:'',dropoff:'',paymentMethod:'CASH',platformId:'',toll:'0',parking:'0'});
useEffect(()=>{const a=()=>setOffline(!navigator.onLine);addEventListener('online',a);addEventListener('offline',a);navigator.serviceWorker?.register('/sw.js');SB.auth.getSession().then(({data})=>{setS(data.session);setLoading(false);if(data.session) refresh(data.session,true);else if(!ctx)setScreen('login')});return()=>{removeEventListener('online',a);removeEventListener('offline',a)}},[]);
async function refresh(sess=s,initial=false){if(!sess)return;try{const d=await api('/v1/me/driver-context',sess.access_token);const c=d.context||d;localStorage.setItem(key,JSON.stringify(c));setCtx(c);setScreen('home');setErr('')}catch(e){if(ctx||localStorage.getItem(key)){setScreen('home');setErr('Offline mode: using cached driver profile')}else{setErr(String(e));if(initial)setScreen('login')}}}
async function login(email:string,password:string){setErr('');const{data,error}=await SB.auth.signInWithPassword({email,password});if(error){setErr(error.message);return}setS(data.session);await refresh(data.session)}
async function logout(){await SB.auth.signOut();localStorage.removeItem(key);localStorage.removeItem('cab-session-id');setCtx(null);setSessionId(null);setScreen('login')}
function enqueue(type:string,body:any){const x:{id:string;type:string;body:any;status:string}={id:crypto.randomUUID(),type,body,status:'PENDING_SYNC'};const q=[...readQ(),x];saveQ(q);setQueue(q);return x.id}
async function sync(){if(!s||!navigator.onLine)return;let q=readQ();for(const x of q){try{let path=x.type==='SESSION_START'?'/v1/sessions':x.type==='SESSION_CLOSE'?'/v1/sessions/'+x.body.sessionId+'/close':x.type==='TRIP_START'?'/v1/trips/start':x.type==='TRIP_END'?'/v1/trips/end':x.type==='TRIP'?'/v1/trips':x.type==='FUEL'?'/v1/fuel':'/v1/expenses';await api(path,s.access_token,x.body);if(x.type==='SESSION_START'&&x.body.sessionId)localStorage.setItem('cab-session-id',x.body.sessionId);q=q.filter(y=>y.id!==x.id);saveQ(q);setQueue(q)}catch(e){break}}}
useEffect(()=>{sync();const t=setInterval(sync,30000);return()=>clearInterval(t)},[s]);
async function start(){if(!ctx?.vehicleId||!s)return;let gps:any={};try{gps=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(p=>res({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyMeters:p.coords.accuracy,capturedAtEpochMs:Date.now()}),rej,{enableHighAccuracy:true,timeout:8000,maximumAge:0}))}catch{setErr('GPS is required to start a session');return}const id=crypto.randomUUID();const body={clientTransactionId:id,sessionId:id,startOdometer:Number(odo),latitude:gps.latitude,longitude:gps.longitude,gpsAccuracyM:gps.accuracyMeters,gpsAt:new Date().toISOString(),startedAt:new Date().toISOString()};enqueue('SESSION_START',body);localStorage.setItem('cab-session-id',id);setSessionId(id);setScreen('home');setOdo('');sync()}
async function addTrip(){if(!sessionId){setErr('Start a session first');return}const toll=Number(trip.toll)||0,parking=Number(trip.parking)||0;const body={clientTransactionId:crypto.randomUUID(),sessionId,startOdometer:Number(trip.start),endOdometer:Number(trip.end),grossFare:Number(trip.fare),pickup:trip.pickup||null,dropoff:trip.dropoff||null,paymentMethod:trip.paymentMethod,platformId:trip.platformId||null,additionalCharges:toll+parking,tollCharges:toll,parkingCharges:parking,status:'COMPLETED',startedAt:new Date().toISOString(),endedAt:new Date().toISOString()};enqueue('TRIP',body);setScreen('home');setTrip({start:'',end:'',fare:'',pickup:'',dropoff:'',paymentMethod:'CASH',platformId:'',toll:'0',parking:'0'});sync()}
function closeSession(){if(!sessionId)return;const body={clientTransactionId:crypto.randomUUID(),sessionId,closeOdometer:Number(odo),closedAt:new Date().toISOString()};enqueue('SESSION_CLOSE',body);localStorage.removeItem('cab-session-id');setSessionId(null);setScreen('home');setOdo('');sync()}
if(loading)return <main><h2>Cab Ops</h2><p>Restoring session…</p></main>;if(screen==='login')return <Login onLogin={login} error={err}/>;if(screen==='start')return <Start odo={odo} setOdo={setOdo} onBack={()=>setScreen('home')} onStart={start}/>;if(screen==='trip')return <Trip t={trip} setT={setTrip} onBack={()=>setScreen('home')} onSave={addTrip}/>;if(screen==='close')return <Start odo={odo} setOdo={setOdo} onBack={()=>setScreen('home')} onStart={closeSession} close/>;return <main><header><div><b>Cab Ops</b><div className="muted">{ctx?.displayName} • {ctx?.registrationNumber||'No vehicle'}</div></div><button onClick={logout}>Logout</button></header>{offline&&<div className="banner">OFFLINE • Local changes will sync automatically</div>}{err&&<div className="error">{err}</div>}<section className="card"><small>TODAY</small><div className="stats"><b>{ctx?.today?.trips||0}<small>Trips</small></b><b>{Number(ctx?.today?.distanceKm||0).toFixed(1)}<small>KM</small></b><b>₹{Number(ctx?.today?.earnings||0).toFixed(0)}<small>Earnings</small></b></div></section>{sessionId?<section className="card"><h2>SESSION ACTIVE</h2><p>Start KM: {odo||'—'} • {queue.length?queue.length+' pending':'Syncing'}</p><button onClick={()=>setScreen('trip')}>ADD TRIP</button><button onClick={()=>setScreen('close')}>END SESSION</button></section>:<section className="card"><h2>READY TO WORK</h2><button className="primary" onClick={()=>setScreen('start')}>START SESSION</button></section>}<section className="card"><b>Sync queue</b><p>{queue.length} pending item(s)</p><button onClick={sync}>SYNC NOW</button></section></main>}
function Login(p:{onLogin:(e:string,p:string)=>void;error:string}){const[e,setE]=useState(''),[pw,setP]=useState('');return <main><div className="login"><h1>Cab Ops</h1><p>Driver login</p><input placeholder="Email" value={e} onChange={x=>setE(x.target.value)}/><input placeholder="Password" type="password" value={pw} onChange={x=>setP(x.target.value)}/><button className="primary" onClick={()=>p.onLogin(e,pw)}>SIGN IN</button>{p.error&&<div className="error">{p.error}</div>}</div></main>}
function Start({odo,setOdo,onBack,onStart,close=false}:{odo:string;setOdo:(x:string)=>void;onBack:()=>void;onStart:()=>void;close?:boolean}){return <main><h2>{close?'End':'Start'} Session</h2><p>Current Odometer (km)</p><input className="odo" inputMode="numeric" autoFocus value={odo} onChange={e=>setOdo(e.target.value.replace(/[^0-9.]/g,''))}/><div className="row"><button onClick={onBack}>CANCEL</button><button className="primary" onClick={onStart}>{close?'END SESSION':'START SESSION'}</button></div></main>}
function Trip({t,setT,onBack,onSave}:{t:any;setT:(x:any)=>void;onBack:()=>void;onSave:()=>void}){const f=(k:string)=>(e:any)=>setT({...t,[k]:e.target.value});return <main><h2>Add Trip</h2>{['start','end','fare','pickup','dropoff','platformId','toll','parking'].map(k=><input key={k} placeholder={k} value={t[k]} onChange={f(k)} inputMode={['start','end','fare','toll','parking'].includes(k)?'decimal':undefined}/>)}<select value={t.paymentMethod} onChange={f('paymentMethod')}><option>CASH</option><option>UPI</option><option>CARD</option></select><div className="row"><button onClick={onBack}>CANCEL</button><button className="primary" onClick={onSave}>SAVE TRIP</button></div></main>}
createRoot(document.getElementById('root')!).render(<App/>);