'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { getSupabaseBrowserClient } from '../../lib/supabase-browser';

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:3000';
type Driver = { id:string; email:string|null; user:{display_name:string;phone:string|null;is_active:boolean}|null; employee_code:string|null; license_number:string|null; license_expiry:string|null; vehicle:{registration_number:string;make:string;model:string;variant:string|null;fuel_type:string;current_odometer:number|string;status:string}|null };

export default function DriversPage() {
  const [drivers,setDrivers]=useState<Driver[]>([]); const [selected,setSelected]=useState<Driver|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [showCreate,setShowCreate]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const [form,setForm]=useState({email:'',password:'',displayName:'',phone:'',employeeCode:'',licenseNumber:'',licenseExpiry:'',registrationNumber:'',make:'Hyundai',model:'Aura',variant:'',fuelType:'CNG',currentOdometer:'0',isActive:true});
  const supabase=getSupabaseBrowserClient();
  const update=(key:keyof typeof form,value:string|boolean)=>setForm(v=>({...v,[key]:value}));
  async function token(){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token){window.location.replace('/login');return null;}return session.access_token;}
  async function load(){setLoading(true);setError('');try{const t=await token();if(!t)return;const r=await fetch(`${API}/v1/admin/drivers`,{headers:{Authorization:`Bearer ${t}`}});const d=await r.json().catch(()=>({}));if(r.status===401||r.status===403){await supabase.auth.signOut();window.location.replace('/login');return;}if(!r.ok)throw new Error(d.message||d.error||`HTTP ${r.status}`);setDrivers(d.drivers??[]);}catch(e){setError(e instanceof Error?e.message:'Unable to load drivers');}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);

  async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const t=await token();if(!t)return;const r=await fetch(`${API}/v1/admin/drivers`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({...form,phone:form.phone||null,employeeCode:form.employeeCode||null,licenseNumber:form.licenseNumber||null,licenseExpiry:form.licenseExpiry||null,variant:form.variant||null,currentOdometer:Number(form.currentOdometer)})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`HTTP ${r.status}`);setMessage(`Driver created. Vehicle ${d.registrationNumber} is assigned.`);setShowCreate(false);setForm({...form,email:'',password:'',displayName:'',phone:'',employeeCode:'',licenseNumber:'',licenseExpiry:'',registrationNumber:'',currentOdometer:'0',isActive:true});await load();}catch(e){setError(e instanceof Error?e.message:'Unable to create driver');}finally{setBusy(false);}}
  function edit(d:Driver){setSelected(d);setForm(v=>({...v,email:d.email??'',password:'',displayName:d.user?.display_name??'',phone:d.user?.phone??'',employeeCode:d.employee_code??'',licenseNumber:d.license_number??'',licenseExpiry:d.license_expiry??'',registrationNumber:d.vehicle?.registration_number??'',make:d.vehicle?.make??'Hyundai',model:d.vehicle?.model??'Aura',variant:d.vehicle?.variant??'',fuelType:d.vehicle?.fuel_type??'CNG',currentOdometer:String(d.vehicle?.current_odometer??0),isActive:d.user?.is_active??true}));setMessage('');setError('');}
  async function save(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError('');setMessage('');try{const t=await token();if(!t)return;const r=await fetch(`${API}/v1/admin/drivers/${selected.id}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify({displayName:form.displayName.trim(),phone:form.phone.trim()||null,employeeCode:form.employeeCode.trim()||null,licenseNumber:form.licenseNumber.trim()||null,licenseExpiry:form.licenseExpiry||null,isActive:form.isActive})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`HTTP ${r.status}`);setMessage('Driver details updated.');setSelected(null);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to update driver');}finally{setBusy(false);}}

  return <main style={{maxWidth:1100,margin:'0 auto',padding:32,fontFamily:'system-ui'}}>
    <p><Link href="/">← Dashboard</Link></p><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16}}><div><h1 style={{marginBottom:6}}>Drivers & Vehicles</h1><p style={{color:'#666',marginTop:0}}>View existing drivers and edit their profile details.</p></div><button onClick={()=>{setShowCreate(v=>!v);setSelected(null);}}>{showCreate?'Close':'＋ Add driver'}</button></div>
    {message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}
    {showCreate&&<form onSubmit={create} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:14,border:'1px solid #ddd',borderRadius:16,padding:20,marginBottom:24}}><h3 style={{gridColumn:'1/-1',margin:0}}>Create driver</h3>{[['displayName','Driver name','text'],['email','Login email','email'],['password','Temporary password','password'],['phone','Phone','tel'],['employeeCode','Employee code','text'],['licenseNumber','License number','text'],['licenseExpiry','License expiry','date'],['registrationNumber','Vehicle registration','text'],['currentOdometer','Current odometer','number']].map(([k,l,t])=><label key={k}>{l}<input required={['displayName','email','password','registrationNumber','currentOdometer'].includes(k)} type={t} min={t==='number'?'0':undefined} value={String(form[k as keyof typeof form])} onChange={e=>update(k as keyof typeof form,e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',padding:10,marginTop:5}}/></label>)}<div style={{gridColumn:'1/-1',fontSize:13,color:'#666'}}>Vehicle defaults: Hyundai Aura • CNG. Existing vehicle history is never rewritten by driver profile edits.</div><button disabled={busy} type="submit">{busy?'Creating…':'Create driver & assign vehicle'}</button></form>}
    {loading?<p>Loading drivers…</p>:drivers.length===0?<p>No drivers found.</p>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Driver','Email','Phone','Vehicle','Status','Action'].map(h=><th key={h} style={{textAlign:'left',borderBottom:'1px solid #ddd',padding:10}}>{h}</th>)}</tr></thead><tbody>{drivers.map(d=><tr key={d.id}><td style={{padding:10}}>{d.user?.display_name??'—'}</td><td style={{padding:10}}>{d.email??'—'}</td><td style={{padding:10}}>{d.user?.phone??'—'}</td><td style={{padding:10}}>{d.vehicle?.registration_number??'Unassigned'}</td><td style={{padding:10}}>{d.user?.is_active?'Active':'Inactive'}</td><td style={{padding:10}}><button onClick={()=>edit(d)}>Edit</button></td></tr>)}</tbody></table></div>}
    {selected&&<form onSubmit={save} style={{marginTop:24,border:'1px solid #ddd',borderRadius:16,padding:20,display:'grid',gap:14}}><div style={{display:'flex',justifyContent:'space-between'}}><div><h3 style={{margin:0}}>Edit driver</h3><small>{selected.email}</small></div><button type="button" onClick={()=>setSelected(null)}>Cancel</button></div><label>Driver name<input required value={form.displayName} onChange={e=>update('displayName',e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',padding:10,marginTop:5}}/></label><label>Phone<input value={form.phone} onChange={e=>update('phone',e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',padding:10,marginTop:5}}/></label><label>Employee code<input value={form.employeeCode} onChange={e=>update('employeeCode',e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',padding:10,marginTop:5}}/></label><label>License number<input value={form.licenseNumber} onChange={e=>update('licenseNumber',e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',padding:10,marginTop:5}}/></label><label>License expiry<input type="date" value={form.licenseExpiry} onChange={e=>update('licenseExpiry',e.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box',padding:10,marginTop:5}}/></label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={form.isActive} onChange={e=>update('isActive',e.target.checked)}/> Driver account active</label><p style={{margin:0,color:'#666'}}>Vehicle: {selected.vehicle?.registration_number??'Unassigned'} — vehicle editing/reassignment is kept separate so historical sessions remain correct.</p><button disabled={busy} type="submit">{busy?'Saving…':'Save changes'}</button></form>}
  </main>;
}
