create or replace function public.reset_test_driver_data(p_driver_id uuid, p_vehicle_id uuid, p_since timestamptz, p_confirmation text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_reg text; v_assigned boolean; v_ids uuid[]; v_files jsonb; v_count int; v_trip int; v_fuel int; v_exp int; v_ocr int; v_rec int; v_exc int; v_file int; sid uuid; oldj jsonb;
begin
 if p_confirmation <> 'RESET_GJ01NT0088' then raise exception using errcode='42501',message='TEST_RESET_CONFIRMATION_REQUIRED'; end if;
 select registration_number into v_reg from vehicles where id=p_vehicle_id;
 if v_reg is distinct from 'GJ01NT0088' then raise exception using errcode='42501',message='TEST_RESET_VEHICLE_SCOPE_DENIED'; end if;
 select exists(select 1 from driver_vehicle_assignments where driver_id=p_driver_id and vehicle_id=p_vehicle_id and assigned_to is null) into v_assigned;
 if not v_assigned then raise exception using errcode='42501',message='TEST_RESET_DRIVER_SCOPE_DENIED'; end if;
 select coalesce(array_agg(id order by started_at),'{}') into v_ids from sessions where driver_id=p_driver_id and vehicle_id=p_vehicle_id and created_at>=p_since;
 select coalesce(jsonb_agg(jsonb_build_object('id',f.id,'bucket',f.bucket,'object_path',f.object_path)),'[]'::jsonb) into v_files from files f where f.id in (select start_odometer_file_id from sessions where id=any(v_ids) and start_odometer_file_id is not null union select close_odometer_file_id from sessions where id=any(v_ids) and close_odometer_file_id is not null union select receipt_file_id from fuel_transactions where session_id=any(v_ids) and receipt_file_id is not null union select proof_file_id from expenses where session_id=any(v_ids) and proof_file_id is not null);
 select count(*) into v_count from sessions where id=any(v_ids); select count(*) into v_trip from trips where session_id=any(v_ids); select count(*) into v_fuel from fuel_transactions where session_id=any(v_ids); select count(*) into v_exp from expenses where session_id=any(v_ids); select count(*) into v_ocr from ocr_verifications where session_id=any(v_ids); select count(*) into v_rec from reconciliations where session_id=any(v_ids); select count(*) into v_exc from exceptions where entity_id=any(v_ids); select count(*) into v_file from files where id in (select (x->>'id')::uuid from jsonb_array_elements(v_files)x);
 foreach sid in array v_ids loop select to_jsonb(s) into oldj from sessions s where s.id=sid; insert into audit_logs(id,entity_type,entity_id,action,old_data,new_data,reason,created_at) values(gen_random_uuid(),'SESSION',sid,'TEST_RESET',oldj,jsonb_build_object('deleted',true,'scope','GJ01NT0088','since',p_since),'Deliberate QA/test reset; test vehicle only',now()); end loop;
 delete from ocr_verifications where session_id=any(v_ids); delete from reconciliations where session_id=any(v_ids); delete from exceptions where entity_id=any(v_ids); delete from trips where session_id=any(v_ids); delete from fuel_transactions where session_id=any(v_ids); delete from expenses where session_id=any(v_ids); delete from sessions where id=any(v_ids); delete from files where id in (select (x->>'id')::uuid from jsonb_array_elements(v_files)x);
 return jsonb_build_object('scope','GJ01NT0088','driver_id',p_driver_id,'vehicle_id',p_vehicle_id,'since',p_since,'sessions_deleted',v_count,'trips_deleted',v_trip,'fuel_deleted',v_fuel,'expenses_deleted',v_exp,'ocr_deleted',v_ocr,'reconciliations_deleted',v_rec,'exceptions_deleted',v_exc,'files_deleted',v_file,'storage_files',v_files,'reset_at',now());
end; $$;
revoke all on function public.reset_test_driver_data(uuid,uuid,timestamptz,text) from public,anon,authenticated;
grant execute on function public.reset_test_driver_data(uuid,uuid,timestamptz,text) to service_role;
